# Generated by Django 5.0.2 on 2024-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productCategory', models.CharField(max_length=200)),
                ('productWarranty', models.CharField(max_length=200)),
                ('productPrice', models.FloatField(max_length=30)),
                ('productBrand', models.CharField(max_length=100)),
            ],
        ),
    ]
