# Generated by Django 5.0.2 on 2024-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=30)),
                ('Cid', models.IntegerField()),
                ('Cage', models.IntegerField()),
                ('CmailId', models.CharField(max_length=50)),
            ],
        ),
    ]
